apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  labels:
    app: goapp
spec:
  selector:
    matchLabels:
      app: goapp
  replicas: 3
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: goapp
          image: goapp
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
